server:
  port: 8080

spring:
  application:
    name: safeops-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:safeOps_DB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Shikha@123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


  jackson:
    serialization:
      write-dates-as-timestamps: false

# SafeOps custom config
safeops:
  model-service:
    base-url: http://${MODEL_SERVICE_HOST:localhost}:${MODEL_SERVICE_PORT:8000}
    timeout-seconds: 15
  safety-engine:
    base-url: ${SAFETY_ENGINE_BASE_URL:https://monkey3770-safeops-ai-engine.hf.space}
    timeout-seconds: ${SAFETY_ENGINE_TIMEOUT_SECONDS:20}
  simulator:
    fixed-delay-ms: ${SENSOR_SIMULATOR_FIXED_DELAY_MS:5000}
  jwt:
    secret: ${JWT_SECRET:dGhpcyBpcyBhIHZlcnkgc2VjcmV0IGtleSBmb3IgSldUIHRva2VucyBpbiBTYWZlT3BzIEFJIGJhY2tlbmQ=}
    access-token-expiration-ms: 3600000    # 1 hour
    refresh-token-expiration-ms: 86400000  # 24 hours

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc / Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

logging:
  level:
    com.safeops.backend: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
