
-- Disabled/safer migration: make idempotent to avoid failures if the table already exists
CREATE TABLE IF NOT EXISTS sensor_readings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sensor_id       VARCHAR(50) NOT NULL,
    value           DOUBLE PRECISION NOT NULL,
    anomaly_score   DOUBLE PRECISION DEFAULT 0.0,
    ts              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_sensor_readings_sensor_id_ts ON sensor_readings(sensor_id, ts DESC);


